We have to check for completeness of the stack, not just any old resource

diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -95,18 +95,25 @@ while [ "$COMPLETE" == "false" ]; do
     --max-items 20 \
     --query 'StackEvents' | jq 'map(select(.Timestamp > "'$TOUCHED'"))' > /tmp/events.json
 
-  TOUCHED=$(jq -r '.[0].Timestamp // "'$TOUCHED'"' /tmp/events.json)
-  COMPLETE=$(jq -r '.[0].ResourceStatus // "" | endswith("_COMPLETE")' /tmp/events.json)
-
   jq -r 'def pad($l): .[:$l] + ($l - (. | length)) * " "; reverse | map([(.ResourceStatus | pad(30)), (.ResourceType | pad(30)), (.LogicalResourceId | pad(25)), .ResourceStatusReason])[] | join(" | ")' /tmp/events.json
 
+  # FIXME: we should probably have a maximum number of iterations to approximate a timeout
+
+  COMPLETE=$(jq -r '.[0].ResourceType == "AWS::CloudFormation::Stack" and (.[0].ResourceStatus // "" | (endswith("_COMPLETE") or endswith("_FAILED"))' /tmp/events.json)
   if [ "$COMPLETE" == "false" ]; then
+    TOUCHED=$(jq -r '.[0].Timestamp // "'$TOUCHED'"' /tmp/events.json)
     sleep 3
   fi
 done
 
 
-# if CREATE_COMPLETE or UPDATE_COMPLETE then output version, otherwise explode
+# We consider anything that wasn't UPDATE_COMPLETE to be a failure
+if jq -er '.[0].ResourceStatus != "UPDATE_COMPLETE"' > /dev/null; then
+  exit 1
+fi
+
+
+# Fetch final state of the stack
 aws cloudformation describe-stacks \
   --stack-name "$STACK" \
   --query 'Stacks[0]' > /tmp/output
